name: Checks
'on':
  - push
jobs:
  lint-test-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Copy library
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependancies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --collectCoverage --coverageDirectory=output/

      - name: Upload an artifact
        run: ls -la
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: ./output/lcov.info

