name: Info Workflow
'on':
  - push
jobs:
  run-info-command:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Project Info
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          ls -la
      - name: Versions
        run: |
          node -v 
          npm -v
